linters:
  enable-all: true
  disable:
    - deadcode
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - govet
    - lll
    - maligned
    - nakedret
    - unparam
    - unused
    - varcheck
